
# # The domain to access Operations Manager;
opsman_domain_or_ip_address: https://pcf.dorris.cf-app.com
# Operations Manager credentials to set
# opsman_admin_username/opsman_admin_password needs to be specified
opsman_admin_username: pivotalcf
opsman_admin_password: fxtae6y139g83q4t

# Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: haUNsCVJEeLUPJRyxAFD

# PCF Ops Manager minor version to track
pasw_major_minor_version: ^2\.1\.[0-9]+$ # Ops Manager minor version to track (e.g ^2\.0\.[0-9]+$ will track 2.0.x versions)

# IaaS for downloading the correct Stemcell: aws, azure, gcp
iaas: gcp

git_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEAuVVpr7A82rog9E7AO8OCdfCaJkoXFBuDhbzuiWLn6odCm1J7
    8IrDWV2yW/Emd42WTZrSf7h9JAhoAHwIHcdtKtuIuL7aNcxDIQgupiUNoqDHZet8
    vagI9a/tlHlwAJPjys2ubin2GNJaQudbZjDuYznXmnLgqqPxdwIn7lUGsdPRx7EY
    A33zb5qobUGfTzUEVWJxabgZW8adc7WXdk9xSjtsXId1LmdWi8NJhd/0/0Xu+Pc/
    0RTRmJTwN0CgIGE+Y0HxXZceVwPScHTCQGVDu7xHlcAPG/qm00JrnO15aoHROJKY
    gWiAn4j/UW5LCtgSetfu0ho2PNaXoB7qtg6p8U8XiLvcas6pgHBZ6yQCqSrKqZjk
    v2VYLr5ex3rgghgk9QMdn9ICsIgNVgyEv/KEhynKZgzVw76Km6RnMd5yu5/6oPLm
    dYxgpw1ft5CZE195AzK6aj3zQyubh6VSAcbIZTlJW94ZseXUERPrvA4660NaN2VW
    HRMLsEtyWBsiw20Hg2oIdzX6IgXIVQKBxMscj4yAl/WXXdn4Fx3v8IRLsVjDCfeI
    xnx4yCocEoor/k9xs686F3hUxUryjSpfzqAgWuKQlosDueVbgNlo748x+9+JeP4r
    qFSw//opFq6RRzD8nzntU3nAVKztAKMVp8chQnT5C7Z4tp1bp7hi21GO3m8CAwEA
    AQKCAgBrz9AHL9J2usfo1tbk7Tq7ORezJm5+d/LunZV1vl+DAuQwTq9iopY5KlRT
    P9lMusSwqFvDiKLjjzBQ99YQ3K4YvFSwg/WUThrO4F+irvNbo4PbOj36ZgGwSoM+
    V9Zbv6xHkZbi5u4OSm/Pc56rt9M1TbSqWCFxoqUYwdxQvI2EbOAf9lktztsKFUHd
    LMtr3D+FHBs1kK7PwJ5fbUeKv3P75s2GlhYIxHyIGTZv9nQi+5+knNA25JF43UtQ
    GPwNWgRc4UNzWjGAFO0aFhHaPA5G66QI7QzdDdZ2FrFbPJng51u6OS0WOqB4Lc24
    pRxqVn+JjouTFURv57WUo+eNuMIKbFcJbmXrEwMUR53PqPPJt6TW7XWN3iCwMxaW
    oi2vTsHNgpRBBKiRqJAOheHAGm8fgZBCZZMSai6ndbo2aFmPXXAMxxZEkUIQz9nB
    sk33CXpGlbY/okt2TezPW+V4Peitz6NED7mrHTOr75+AxW+1UZGEv0SDYav3VJwt
    MBqz1nNTuJgG9AxMR95o6aM0LF40RSEldjQnvQVB3wOtxPEvRGv/3V6jhkVqrstj
    Vpcn87Na6zxCAIkEGzZktn3EEdKAPZT9PaTAYfVeYiGONJu+kvqRjhhDoEHN8/h/
    ShGl0DUHBXWj8fcSSyLFHLH6jmqvMYAHnd4WunNdO+PbWP5BoQKCAQEA5gzDnPJJ
    VT0sgJWqk852+VDD27Dv6znBPjmPhsSWUuQ/VlyhbaRTxlJ8umJkOtI2Jw6/bNE3
    0iii4ODxqn3PanqmY/cRqw40NzoC/qm57rNylM0UR7BScsVGpRKlY+0ydCgf6z50
    Fm8E17PafO20tMdD/e6TJsexahoP8hX+xP6kcxF3lAhRqWtJJ+IbMid3zkS/SlM6
    CH7SY/Cko/lOcTPsYPghrBaiHPc2wM4b5v8w8XnvvYDh/9ayEZq0OYqVufYJE6ZI
    MLb0XUmLEMx1bhacYvCV89jVRumX13Psi7eT9MfRml9kBvKfokRsZ4p0behy09ui
    CPs4p6c/4jJTCwKCAQEAzj1coHafwzE9wlwRdauR0VP7KF6TXfrE7jKjCcGATUNQ
    MjwfEv/2MuDcjs747SAvwPSDX2/nqvH7hxsNgF9zRDI0eUQHB3+4XQvh/UuoQCx2
    zgb6UB0Cp630qTCIjDbKtp5LiLjXiTEKK/jP1XfmzUW9i37V0FX8Iv5KLEYWVDzp
    F2LeyFvoWGyDI0Bn3+ehudib8YwVhV+ZF1MKLFeD4KJYX/gg2JidHntAf0w4coY8
    KdATH4En1n51WKAuQLjxSd/pjPJlAnhxXCIThiVc33VbKjg9blGBEbJ8pb1+FoSg
    TEloycpBWNRsqfWGQXGzYar6uPFV2Fg3hkN+4J5ArQKCAQEA48ERTOmmZohY7bi/
    FvRaX3xxW6gx7wzP3333NbKdLNWiSysL+tOsyPTTXWeZ2Y5SZJq6M85yWFM45jBt
    saA64C0rXF64FETMtzxsyJlaZhMsxlq+0DaledELntP2ABdOUyeCalD7d1ZUUgVS
    s0pXFH8PNnCjKMqdP/Erhj32bCu6vd02KM2Po45+78hvqljeyMzRIZGCK/T68EzH
    gzuISJTiWiJum8QQnWK2x22GvEw7tWZGTrQxiyuQQdOKyEkG8QO/er+uSuRmy5DK
    6Eezntkt3NpZawBqLnmHhZvUPYLzLW1Ce3YjPqmoF2tsc5nkqQdv34VbR08IiRsR
    KS0vfwKCAQA48liRNjAHBaG3+RQZGba5xiajjvnCCWw3GWRLXVLAAsYyGMe7x1GD
    2vMLu7qgPzLwZJOh1pRxbz+0npOrzq9VNUen9FC8kVem2ZEdD7b1gVGMsgCL/nat
    NitITE5n6PkwU6Unq2JYT2IvohRBLUpdg9RCoFMJo7RrNSvl7bRcrjTucC5zxGzz
    fYL4SOBlwt+1IUpt9/A5U5xCBHvaoo+Xhzw/w5POOtWnhQDaJYGwncAfC4U8Pb1y
    TJi6UAB1fpuhemJSuNuLQxaKCh65+7cZPJ5fmgfcXkT1TgN9AEXAkf5xEhQNI/vH
    O2CFzXW0vGB7p2pzhq/dfP5X5Gs0On5BAoIBAQCIc5LJY15nwz3JpA66OQPhH1+e
    T1+YO5Xly/gDl/GZ93N/9ShR9AV2TVTtn0qlMh9Dz/zP6ehPDzg5i/KHGDEKfRYg
    99f4oHjwuWrGEa6H8qJS7pKdpuK3ZjnYSEdCl5G5xPqFj/6rb+ZDtpsvx0biPSv7
    FoUW0Gu6eVbB7CbitAWGleUCzTa4vNMxuQZUfNdA1GIEku5CO0lhBs+Z++hG5fCY
    pHhCwQw3sdYVex5NoFjKaTx2dO62HgrZCVhe+na4+lZ5v5DJtfzyrzxH+ajwwkfl
    0DhOVQRT/ZXXjksgwyDikTv5dUf3pJrlQKPsCOfyxbRxHYs/tQnBPvEu4+Fk
    -----END RSA PRIVATE KEY-----
