resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:kartiklunkad26/pcf-pipelines.git
    branch: deploy-pasw
    private_key: {{git_private_key}}

- name: pivnet-pasw
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pas-windows
    product_version: {{pasw_major_minor_version}}
    sort_by: semver

- name: pivnet-winfs-injector
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pas-windows
    product_version: {{pasw_major_minor_version}}
    sort_by: semver

jobs:
- name: build-pasw-injected
  plan:
  - get: pcf-pipelines
    trigger: true
  - get: pivnet-pasw
    params:
      globs:
      - "*.pivotal"
  - get: pivnet-winfs-injector
    params:
      globs:
      - "*injector*"
  - task: build-injected-pasw
    file: pcf-pipelines/deploy-pasw/tasks/build-injected-pasw/task.yml
  - task: upload-injected-pasw
    file: pcf-pipelines/deploy-pasw/tasks/upload-injected-pasw/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: ""
      OM_IP: ""
